### ISSUE TITLE
Passive mobs constantly run around at night

### ISSUE THREAD

**Issue by turabian-luvr** [seymourimadeit/Big-Brain#18]
At night in open biomes like plains, passive mobs run in random directions constantly.

I assume this is related to the "find shelter" feature. It seems like they should knock it off after a few seconds, or move at a normal speed when seeking shelter.

**Comment by seymourimadeit** [comment]
non issue, works as intended.

**Comment by IdrisQe** [comment]
Replying to this since this... well, even if it's intended, it... feels like it shouldn't be?

Having night hit and for the next 10 minutes every passive mob just flails around at hyperspeed even if there's no shelter nearby that they could enter (as is the case in a lot of biomes like plains, deserts, snow fields...) There really should be a limit to how much they'll do it, or they should do it at normal speed, since currently it looks more like mobs are over-caffinated at night, rather than seeking a place to rest. It looks more like a glitch than an AI tweak in most circumstances.
